### ISSUE TITLE
Karma should be a peer dependency

### ISSUE THREAD

**Issue by raphael-boucher** [karma-runner/karma-jasmine#101]
Hello,

For usage in npm 3 with peer dependencies, karma should be in the peer dependencies list.

For more details: https://nodejs.org/en/blog/npm/peer-dependencies/

Thanks!

**Comment by mrzepinski** [comment]
+1

**Comment by eddiemonge** [comment]
i think it should actually be a dependency, along with jasmine-core

**Comment by maksimr** [comment]
@raphael-boucher, @mrzepinski  why you want add `karma` as peer dependency?

**Comment by ilkkao** [comment]
No, it's other way around. Current warning:

```
npm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```
`jasmine-core` should be moved from peerDependencies to dependencies section.

**Comment by maksimr** [comment]
@ilkkao why? With peerDependency you can use any version of `jasmine-core` what you want. If we move it to dependency then you can only use version which shipped with karma-jasmine.

**Comment by ilkkao** [comment]
Right, npm3 will show that same warning and additionally doesn't install `jasmine-core` if it is missing. Maybe the README should then just remind also to install `jasmine-core`.

Just thinking how to remove the warning, it's the only one I see in my project.

**Comment by eddiemonge** [comment]
You can specify ` >x.x.x` range in dependencies. Dependencies get installed, peerDepedencies don't.

**Comment by maksimr** [comment]
@ilkkao 

>  Maybe the README should then just remind also to install jasmine-core

README already describe it
![](https://sc-cdn.scaleengine.net/i/1b6ae0684d4f8f77ba680d0f00d88de6.png)

@eddiemonge For example you are use custom build of jasmine-core.
`karma-jasmine` is adapter, it is should not install own jasmine-core and karma but it should depends from them, with peerDependencies we explicity depends from them.

Thanks

**Comment by ilkkao** [comment]
Nice, I should have fully read the README. 

Npm 3 (current stable version) ignores peerDependencies section and just spits out a warning if it founds one. It will not install or check anything mentioned on it. At some point it should be removed from package.json.

**Comment by ilkkao** [comment]
I was wrong above, peerDependencies are still useful in npm3. If they are not met, warning is shown during npm install.

**Comment by raphael-boucher** [comment]
@maksimr see https://github.com/npm/npm/releases/tag/v3.0.0 (peer dependencies part). Especially
> peerDependencies no longer cause anything to be implicitly installed. Instead, npm will now warn if a packages peerDependencies are missing, but it's up to the consumer of the module (i.e. you) to ensure the peers get installed / are included in package.json as direct dependencies or devDependencies of your package.
  
`karma-jasmine` is a plugin for karma, as well as `jasmine-core` so it should have those two in the peer dependencies. It's useful when installing and when there are compatibility issues with the main libraries.
