### ISSUE TITLE
The --grep option only works if it's the last argument

### ISSUE THREAD

**Issue by ArthurThornton** [karma-runner/karma-jasmine#102]
Some background: I'm working on a grunt task for an internal project with the intention of mimicking rspec's ability to pass in a line number in a spec file and have it correctly set the appropriate `grep` to match that spec. Everything is working up until it gets processed by `karma-jasmine`'s adapter on line 267 (https://github.com/karma-runner/karma-jasmine/blob/76170f6cbc8902716fbac216b4bc1d681c8b39a2/src/adapter.js#L267)

The way that regex is formatted will only work if the `--grep` argument is the very last one, so if you set it via the grunt configuration, or even in the karma.conf.js with an option following it, the grep value gets set incorrectly.

For example, take these args:

```
['--grep=spec1', '--files=path/to/file.js']
```
Line 267 will produce a `--grep` value of:
```
--grep=spec1=--files=path/to/file.js
```

I was able to confirm this (and temporarily fix on my own machine) with this alteration to the regex, however it's not perfect since a spec name **can** have an equal sign in it, therefore this wouldn't work all the time:

```
var match = /--grep=([^=]+)/.exec(clientArgString);
```

**Comment by maksimr** [comment]
@ArthurThornton thanks! Pull Request is welcome
