### ISSUE TITLE
v0.3.7 does not work in ie8

### ISSUE THREAD

**Issue by eGavr** [karma-runner/karma-jasmine#105]
Hi!

From `v0.3.7` you've added [some code](https://github.com/karma-runner/karma-jasmine/blob/v0.3.7/src/adapter.js#L264) which does not work in ie8 (`indexOf`).

**Comment by AndyOGo** [comment]
Same for me breaks with browsers who don't nativly support Array.prototype.indexOf

**Comment by minkyu-yi** [comment]
Same for me.
Use 0.3.5, it works well.
