### ISSUE TITLE
npm install karma-jasmine@2_0 failed optional dependency not compatible with operating system

### ISSUE THREAD

**Issue by winnemucca** [karma-runner/karma-jasmine#107]
I installed karma-jasmine but am getting some wierd warnings on windows 10.  I have node 5.4 installed.

   ````
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup  Not compatible with your operating system or architecture: fsevents@1.0.8 
````

The set second one seems like a pretty significant warning.

**Comment by dignifiedquire** [comment]
As from the `npm WARN` indicated it's just a warning. `fsevents` native dependencies are not supported on Windows, but it has a javascript based fallback so don't worry about it, it should work fine.
