### ISSUE TITLE
Intermittent Script Error. 

### ISSUE THREAD

**Issue by deejaygeekout** [karma-runner/karma-jasmine#109]
Sometimes my CI build is successful sometimes not but it has same config. I only have 69 test cases but it has added one that makes mine total of 70. But it gets Script error in the last part.

This breaks my CI. it's so weird.

Log when it builds successfully.
build   10-Mar-2016 18:16:26    PhantomJS 2.1.1 (Linux 0.0.0): Executed 64 of 70 (skipped 5) SUCCESS (0 secs / 0.95 secs)
build   10-Mar-2016 18:16:26    [1A[2KLOG: 'Success'
build   10-Mar-2016 18:16:26    PhantomJS 2.1.1 (Linux 0.0.0): Executed 64 of 70 (skipped 5) SUCCESS (0 secs / 0.95 secs)
build   10-Mar-2016 18:16:26    [1A[2KPhantomJS 2.1.1 (Linux 0.0.0): Executed 65 of 70 (skipped 5) SUCCESS (0 secs / 0.978 secs)
build   10-Mar-2016 18:16:26    [1A[2KPhantomJS 2.1.1 (Linux 0.0.0): Executed 65 of 70 (skipped 5) SUCCESS (0.856 secs / 0.978 secs)
simple  10-Mar-2016 18:16:27    Finished task 'karma' with result: Success

When error occurs. even log debug is enabled. It's not saying anything

> build 10-Mar-2016 18:30:33    PhantomJS 2.1.1 (Linux 0.0.0): Executed 64 of 70 (skipped 5) SUCCESS (0 secs / 0.982 secs)
> build   10-Mar-2016 18:30:33    [1A[2KPhantomJS 2.1.1 (Linux 0.0.0): Executed 65 of 70 (skipped 5) SUCCESS (0 secs / 1.01 secs)
> build   10-Mar-2016 18:30:33    [1A[2KPhantomJS 2.1.1 (Linux 0.0.0) ERROR
> build   10-Mar-2016 18:30:33      Script error.
> build   10-Mar-2016 18:30:33    PhantomJS 2.1.1 (Linux 0.0.0): Executed 65 of 70 (skipped 5) ERROR (0 secs / 1.01 secs)
> build   10-Mar-2016 18:30:33    [1A[2KPhantomJS 2.1.1 (Linux 0.0.0): Executed 65 of 70 (skipped 5) ERROR (0.839 secs / 1.01 secs)
> build   10-Mar-2016 18:30:33    [36m10 03 2016 18:30:33.288:DEBUG [karma]: [39mRun complete, exiting.
> build   10-Mar-2016 18:30:33    [36m10 03 2016 18:30:33.289:DEBUG [launcher]: [39mDisconnecting all browsers
> build   10-Mar-2016 18:30:33    [36m10 03 2016 18:30:33.311:DEBUG [coverage]: [39mWriting coverage to /home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/coverage/PhantomJS 2.1.1 (Linux 0.0.0)
> build   10-Mar-2016 18:30:33    [36m10 03 2016 18:30:33.370:DEBUG [launcher]: [39mProcess PhantomJS exited with code 0
> build   10-Mar-2016 18:30:33    [36m10 03 2016 18:30:33.371:DEBUG [temp-dir]: [39mCleaning temp dir /tmp/karma-75341423
> build   10-Mar-2016 18:30:33    [36m10 03 2016 18:30:33.374:DEBUG [reporter.junit]: [39mJUnit results written to "/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/PhantomJS_2.1.1_(Linux_0.0.0)/reports/junit/TESTS-xunit.xml".
> build   10-Mar-2016 18:30:33    [36m10 03 2016 18:30:33.377:DEBUG [launcher]: [39mFinished all browsers
> simple  10-Mar-2016 18:30:33    Failing task since return code of [/bin/sh /tmp/CIT-SD-AUT-87-ScriptBuildTask-6327011050539878374.sh] was 1 while expected 0

Another logs that I got from debug

> build 10-Mar-2016 19:17:17    PhantomJS 2.1.1 (Linux 0.0.0): Executed 65 of 70 (skipped 5) ERROR (0.865 secs / 0.98 secs)
> build   10-Mar-2016 19:17:17    [1A[2KPhantomJS 2.1.1 (Linux 0.0.0): Executed 65 of 70 (skipped 5) ERROR (0.913 secs / 0.98 secs)
> error   10-Mar-2016 19:17:17    Missing error handler on `socket`.
> error   10-Mar-2016 19:17:17    TypeError: Cannot read property '35598055' of null
> error   10-Mar-2016 19:17:17        at onBrowserComplete (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/.npm/lib/node_modules/karma-junit-reporter/index.js:102:23)
> error   10-Mar-2016 19:17:17        at null.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/.npm/lib/node_modules/karma/lib/events.js:13:22)
> error   10-Mar-2016 19:17:17        at emitTwo (events.js:105:20)
> error   10-Mar-2016 19:17:17        at emit (events.js:185:7)
> error   10-Mar-2016 19:17:17        at onComplete (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/.npm/lib/node_modules/karma/lib/browser.js:142:13)
> error   10-Mar-2016 19:17:17        at Socket.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/.npm/lib/node_modules/karma/lib/events.js:13:22)
> error   10-Mar-2016 19:17:17        at emitTwo (events.js:105:20)
> error   10-Mar-2016 19:17:17        at Socket.emit (events.js:185:7)
> error   10-Mar-2016 19:17:17        at Socket.onevent (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/.npm/lib/node_modules/karma/node_modules/socket.io/lib/socket.js:335:8)
> error   10-Mar-2016 19:17:17        at Socket.onpacket (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/.npm/lib/node_modules/karma/node_modules/socket.io/lib/socket.js:295:12)
> error   10-Mar-2016 19:17:17        at Client.ondecoded (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/.npm/lib/node_modules/karma/node_modules/socket.io/lib/client.js:193:14)
> error   10-Mar-2016 19:17:17        at Decoder.Emitter.emit (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/.npm/lib/node_modules/karma/node_modules/component-emitter/index.js:134:20)
> error   10-Mar-2016 19:17:17        at Decoder.add (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/.npm/lib/node_modules/karma/node_modules/socket.io-parser/index.js:247:12)
> error   10-Mar-2016 19:17:17        at Client.ondata (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CIT-SD-AUT/.npm/lib/node_modules/karma/node_modules/socket.io/lib/client.js:175:18)
> error   10-Mar-2016 19:17:17        at emitOne (events.js:90:13)
> error   10-Mar-2016 19:17:17        at Socket.emit (events.js:182:7)
> build   10-Mar-2016 19:17:17    [36m10 03 2016 19:17:17.680:DEBUG [launcher]: [39mProcess PhantomJS exited with code 1

**Comment by stefcameron** [comment]
I'm seeing the same issue on OSX 10.11 and when running under Linux in TravisCI. No problems running PhantomJS 2.1.1 through Karma on Windows 7.

**Comment by stefcameron** [comment]
For reference: https://travis-ci.org/stefcameron/yllr/builds/123480434

**Comment by maksimr** [comment]
@deejaygeekout  @stefcameron what version karma and jasmine?
Is it reproduced for another test frameworks (mocha)?

Seems that problem is not in karma-jasmine adapter

Thanks

**Comment by stefcameron** [comment]
@maksimr karma 0.13.10 and jasmine-core 2.3.4
https://travis-ci.org/stefcameron/yllr/builds/123482223

**Comment by kostkobv** [comment]
@deejaygeekout @stefcameron seems like problem have been resolved with newer version of karma.
Can the issue be closed now?

**Comment by stefcameron** [comment]
@kostkobv It's working fine for me now with karma@1.1.0 and jasmine-core@2.4.1, thanks for asking! :) This issue can be closed as far as I'm concerned.
