### ISSUE TITLE
Why does the "--grep" option strip regular expression characters?

### ISSUE THREAD

**Issue by jrolfs** [karma-runner/karma-jasmine#111]
The relevant code is [here](https://github.com/karma-runner/karma-jasmine/blob/b2d01b7334ace76b14daab972f669e5811fb341f/src/adapter.js#L280).

I'd like to be able to use proper regular expressions to filter spec names in certain cases, however that seems impossible currently. I'm happy to open a PR to address this but am curious as to why regular expressions are explicitly not supported currently and the best route to address that if possible. Can we detect regular expressions when the string is surrounded by `/`? Eg: `--grep=/^Collection/`

**Comment by maksimr** [comment]
@jrolfs it should work as expected, pass --grep="^Collection"
