### ISSUE TITLE
karma-jasmine reports pending specs as errors when karma-junit-reporter used. 

### ISSUE THREAD

**Issue by staticcat** [karma-runner/karma-jasmine#112]
I have the following pending spec define in a jasmine test.

```
describe("Pending specs", function (){

    xit("can be declared 'xit'", function () {
        expect(true).toBe(false);
    });

    it("can be declared with 'it' but without a function");

    it("can be declared by calling 'pending' in the spec body", function () {
        expect(true).toBe(false);
        pending('this is why it is pending');
    });
});
```

When written out by the karma-junit-reporter I get a skipped and failed result. This leads me to believe the test has been run, or given a result when it should have none. 

I have also reported this to karma-junit-reporter. 
https://github.com/karma-runner/karma-junit-reporter/issues/90

**Comment by maksimr** [comment]
@staticcat karma-jasmine pass flag [skipped](https://github.com/karma-runner/karma-jasmine/blob/master/src/adapter.js#L220)

Seem karma-junit-reporter does not handled this flag

Thanks
