### ISSUE TITLE
Unable to install jasmine-core in npm 3+

### ISSUE THREAD

**Issue by mohuk** [karma-runner/karma-jasmine#113]
```bash
npm WARN EPEERINVALID karma-jasmine@0.3.8 requires a peer of jasmine-core@* but none was installed.
```
Instead of being a `peerDependency`, `jasmine-core` should declared as a `dependency` so it can be safely installed with npm 3+.

**Comment by maksimr** [comment]
@mohuk nope, it's correct behaviour of peerDependency, karma-jasmine does not shipped with jasmine now. You should yourself install needed version of jasmine.
