### ISSUE TITLE
ReferenceError: createSpy is not defined

### ISSUE THREAD

**Issue by klinki** [karma-runner/karma-jasmine#114]
Hi,
I'm getting following error:

`Error: ReferenceError: createSpy is not defined
	    at execute (http://localhost:9876/base/dist/js/tests/unit/Services/Zoom.spec.js:11:23)
	    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js:332:29)
	    at Zone.run (http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js:227:44)
	    at http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js:576:58
	    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js:365:38)
	    at Zone.runTask (http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js:263:48)
	    at drainMicroTaskQueue (http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js:482:36)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js:434:22)
	Error loading http://localhost:9876/base/dist/js/tests/unit/Services/Zoom.spec.js`

when I try to run tests on my Fedora. But when I run the same tests on Windows computer, it works just fine.

I have the same versions of karma-jasmine, karma and jasmine frameworks.

jasmine-core@2.4.1
karma@0.13.22
karma-cli@0.1.2
karma-jasmine@0.3.8
karma-chrome-launcher@0.2.3

Only difference is, Fedora computer is using newer npm and node versions:
npm: 3.8.3
nodeJS: 5.10.1

Windows computer uses: 
npm: 3.3.12
nodeJS: 5.2.0

Strange thing is when I place breakpoint in the crashing line in source codes (using Karma Debug), I can see jasmine object with createSpy function properly defined:

![jasmine](https://cloud.githubusercontent.com/assets/1476175/14404794/0baf7cae-fe7f-11e5-8e21-1bc397001fba.png)

**Comment by maksimr** [comment]
@klinki could you post test file or spec content?

**Comment by klinki** [comment]
```
import {Zoom} from '../../../app/Services/Zoom';
import createSpy = jasmine.createSpy;

describe('Zoom', () => {
    let zoom: Zoom;

    beforeEach(() => {
        zoom = new Zoom();
    });

    it('Should have default ratio 1', () => {
        expect(zoom.getZoomRatio()).toBe(1);
    });

    describe('After changing zoom ratio', () => {
        let newRatio = 2.0;
        let callback = createSpy('zoom callback');

        beforeEach(() => {
            zoom.onZoomChanged.subscribe(callback);
            zoom.setZoomRatio(newRatio);
        });

        it('Should have new ratio', () => {
            expect(zoom.getZoomRatio()).toBe(newRatio);
        });

        it('Should fire event on Observable', () => {
            expect(callback).toHaveBeenCalled();
        });
    });

    describe('ZoomIn', () => {
        let newRatio = 2.0;
        let callback = createSpy('zoom callback');

        beforeEach(() => {
            zoom.onZoomChanged.subscribe(callback);
            zoom.zoomIn();
        });

        it('Should have new ratio', () => {
            expect(zoom.getZoomRatio()).toBe(newRatio);
        });

        it('Should fire event on Observable', () => {
            expect(callback).toHaveBeenCalled();
        });
    });

    describe('ZoomOut', () => {
        let newRatio = 0.5;
        let callback = createSpy('zoom callback');

        beforeEach(() => {
            zoom.onZoomChanged.subscribe(callback);
            zoom.zoomOut();
        });

        it('Should have new ratio', () => {
            expect(zoom.getZoomRatio()).toBe(newRatio);
        });

        it('Should fire event on Observable', () => {
            expect(callback).toHaveBeenCalled();
        });
    });
});
```

I'm using TypeScript with SystemJS modules.

**Comment by maksimr** [comment]
@klinki 

```
import createSpy = jasmine.createSpy;
```

is it valid expression? You use equal(=) in import expression.
For ES6 it's not valid expression as I see - https://developer.mozilla.org/en/docs/web/javascript/reference/statements/import

**Comment by klinki** [comment]
In TypeScript it should be valid expression. It compiles into correct code and runs fine on Windows. 

But I'm wondering why createSpy needs to be imported and other expressions like describe and it don't. That's strange. I guess there is something wrong with type definition file for Jasmine.

**Comment by maksimr** [comment]
@klinki 

>  guess there is something wrong with type definition file for Jasmine

I agree with you. Is it throw error if change createSpy on jasmine.createSpy?

**Comment by klinki** [comment]
It seems to be working now. I will check it again, but I think it should be ok now

**Comment by maksimr** [comment]
@klinki good
