### ISSUE TITLE
The word "base" is replaced with the path without regard for context.

### ISSUE THREAD

**Issue by crmckenzie** [karma-runner/karma-jasmine#115]
Suppose I have an expectation written as such:

```javascript
var result = subject.requestAsJson();
expect(result).toEqual('{ "databaseType": "fredbob" }');
```

I get output in the console that looks like this:

```
Expected '{"dataC:/Users/Me/src/ProjectType":"fredbob" }' 
to equal '{ dataC:/Users/Me/src/ProjectType": "foobar" }'.
```

I'm using jasmine in the context of `gulp -> karma -> require -> jasmine`.

Apparently, I'm not the only one [having the problem](http://stackoverflow.com/questions/35375808/karma-jasmine-weird-behavior-when-using-the-word-base)

According to the StackOverflow question, 'absolute' is also treated oddly.

**Comment by dignifiedquire** [comment]
This is not a karma-jasmine specific issue. Please open an issue on karma-runner/karma.

**Comment by maksimr** [comment]
Close because it's not related to karma-jasmine directly

Thanks
