### ISSUE TITLE
Pattern "<project_root>\node_modules\karma-jasmine\lib\adapter.js" does not match any file.

### ISSUE THREAD

**Issue by MikeCheel** [karma-runner/karma-jasmine#122]
I didn't get this error this morning and I notice the version was bumped to 1.0.0 today. The adapter.js file is missing.

**Comment by MikeCheel** [comment]
Also, after copying the latest from master into the lib directory THAT error goes away but I still get error: You need to include some adapter that implements __karma__.start method!

Everything worked fine this morning.

**Comment by dignifiedquire** [comment]
Same as #123

**Comment by maksimr** [comment]
Duplicate of #123
