### ISSUE TITLE
You need to include some adapter that implements __karma__.start method!

### ISSUE THREAD

**Issue by blacksonic** [karma-runner/karma-jasmine#123]
After upgrading to 1.0 i get this error message, no stack trace.
The only suspicious line is
```Pattern "/home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/karma-jasmine/lib/adapter.js" does not match any file.```
My karma config is:
https://github.com/blacksonic/angular2-esnext-starter/blob/master/tasks/config/karma.js

**Comment by blacksonic** [comment]
That ```adapter.js``` file just disappeared from the files.

**Comment by fabian** [comment]
Same here, suspecting the move of adapter.js is to blame?

```
$ grunt test
[…]
WARN [watcher]: Pattern "[…]/node_modules/karma-jasmine/lib/adapter.js" does not match any file.
[…]
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  You need to include some adapter that implements __karma__.start method!
```

**Comment by fabian** [comment]
adapter.js moved from lib/adapter.js to src/adapter.js

**Comment by blacksonic** [comment]
But only lib folder gets released.

**Comment by dignifiedquire** [comment]
@zzo this sounds like you forgot to build before the release.

**Comment by mattmazzola** [comment]
Also, blocked on this. Is easy work around just to downgrade back to v3.8?

**Comment by zzo** [comment]
Just downgrade I'll have a chance to fix in a bit. Sorry.
No new features in this release no reason to use it.

**Comment by zzo** [comment]
After much hair pulling version 1.0.2 is out with this issue fixed - sorry for the trouble.

  `('load-grunt-tasks')(grunt)`

Is supposed to load in the 'build' task but that was no longer working?  And even if the task was loaded it was never called by anything so I might have messed it up but now I'm hand-loading the 'build' task and added it as a dependency to the 'test' and 'release' grunt tasks.

**Comment by itrew** [comment]
Oh man...I've spent the last several hours trying to figure out what I was doing wrong in setting up a new project. I did a yeoman tutorial last night and everything was working well, then today I went to grunt test and it shit the bed with the same error.

The roll back fixed it.

**Comment by zzo** [comment]
@itrew SO SORRY I did not realize there was a necessary 'build' step for this package, nor was that 'build' step part of the automated release process.  Glad you got back on track with the previous version.  SORRY!
It's fixed at version 1.0.2

**Comment by itrew** [comment]
No worries. I'm just getting started with node and grunt, so this was actually a pretty good learning experience for me. It wasn't till I compared the versions in the package.json between last night and tonight that I noticed the version update and stumbled onto this thread.

**Comment by zzo** [comment]
Ha ya welcome!

**Comment by nigul2009** [comment]
Hi,
I'm having this error with "karma-jasmine": "1.1.0"

keywords if/then/else require v5 option
13 01 2017 13:43:52.116:WARN [karma]: No captured browser, open http://localhost:9876/
13 01 2017 13:43:52.124:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
13 01 2017 13:44:14.014:INFO [Chrome 55.0.2883 (Windows 10 0.0.0)]: Connected on socket /#ItE285KLWbvmLNItAAAA with id manual-8097
Chrome 55.0.2883 (Windows 10 0.0.0) ERROR
 > You need to include some adapter that implements __karma__.start method!

**Comment by maksimr** [comment]
@nigul2009 looks like you have truble with karma.config.js configuration. You should add 'karma-jasmine' to the config

**Comment by WiniLourson** [comment]
Hi,
I'm having the same problem with Karma 1.7.0

07 07 2017 10:37:35.386:WARN [karma]: No captured browser, open http://localhost:9876/
07 07 2017 10:37:35.399:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
07 07 2017 10:37:44.154:INFO [Chrome 58.0.3029 (Windows 10 0.0.0)]: Connected on socket oihXP_wa6JV2xPqiAAAA with id manual-6530
Chrome 58.0.3029 (Windows 10 0.0.0) ERROR
  You need to include some adapter that implements __karma__.start method!

any ideas ?

**Comment by maksimr** [comment]
@WiniLourson could you provide your *karma.config.js*?

**Comment by WiniLourson** [comment]
yeah sure !

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '%BASE_PATH%',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: ['*.js'],


    // list of files to exclude
    exclude: [%EXCLUDE%],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: %PREPROCESSORS%,


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: false,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['chrome'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  })
}

**Comment by maksimr** [comment]
@WiniLourson hm... looks all are correct.
Could you test with diffirent versions of karma for example karma@1.3.0

**Comment by WiniLourson** [comment]
yeah I searched on many forums to find an error but it looks correct... I didn't want to downgrade but I think I have to...
Thanks for help
will give news when it works

**Comment by maksimr** [comment]
@WiniLourson I have checked on MacOs and all works fine.
I have created [gist](https://gist.github.com/maksimr/1c3f37eba0c1cb3a34b97a57e22f2142) could you check it on your machine.

Thanks

**Comment by WiniLourson** [comment]
not working at all,
I finally used Angular.io doc and it works...

thanks for help :)

**Comment by Janatbek** [comment]
@WiniLourson What did you do to make it work? can you point me to that doc?
