### ISSUE TITLE
Jasmine 2.3+ Broken

### ISSUE THREAD

**Issue by daneren2005** [karma-runner/karma-jasmine#126]
I upgraded to Jasmine 2.4.1 recently and running the tests locally in a browser works fine.  When loading through the following snippet both locally and on Codeship it fails:

```
npm install karma
npm install karma-jasmine karma-chrome-launcher karma-firefox-launcher
./node_modules/.bin/karma start
```

I get the error `Cannot read property 'appendChild' of null` on line 154 of `jasmine-html.js` which is the `jasmineDone` function.  After doing some basic debugging it appears that it was just calling jasmineDone without finishing loading everything else.  The `boot.js`'s onload function was never being called, and because of that the reporter was not initialized and ready to go.  It also appears to start before `$(function() { setupTests... });` was called so even if it initialized properly, none of the tests were being run.  I rolled back to Jasmine 2.2.0 which appears to be the latest working version and now it is not a problem.  I would like to be able to upgrade to the latest versions of Jasmine though.

**Comment by dignifiedquire** [comment]
I've just tested this on multiple repos including the tests on `master` here and things seem to be working fine with Jasmine 2.4.1 Do you have  repo that reproduces this consistently?

**Comment by maksimr** [comment]
Close because no feedback
