### ISSUE TITLE
Broken with karma 1.0.0+

### ISSUE THREAD

**Issue by mordocai** [karma-runner/karma-jasmine#127]
I get:

```
Running "karma:unit" (karma) task
20 07 2016 16:55:30.993:INFO [karma]: Karma v1.0.0 server started at http://localhost:9876/
20 07 2016 16:55:30.994:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
20 07 2016 16:55:30.999:INFO [launcher]: Starting browser PhantomJS
20 07 2016 16:55:31.295:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#HSu9Egi3Z5Mxs4sPAAAA with id 42808977
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  You need to include some adapter that implements __karma__.start method!
```

See https://github.com/karma-runner/karma/issues/2194 and https://github.com/Workiva/karma-jspm/issues/162.

My guess from the karma bug report is that having src/adapter.js and lib/adapter.js may be causing issues? Not sure though, i'm very unfamiliar with karma and its plugins.

I've tried with karma 1.0.0 and 1.1.2 with same results. Using karma-jasmine 1.0.2

Edit: To be clear, it works fine with karma 0.13.22

**Comment by otroboe** [comment]
Hey ! You should try with new version, a fix has been released: https://github.com/karma-runner/karma/issues/2194

**Comment by mordocai** [comment]
Confirmed, this works for me as of karma 1.1.2 https://github.com/karma-runner/karma/releases/tag/v1.1.2
