### ISSUE TITLE
Test fail when calling `done(true)`

### ISSUE THREAD

**Issue by NoelBroda** [karma-runner/karma-jasmine#148]
Hi guys!
As I was reading (https://github.com/jasmine/jasmine.github.io/issues/67), jasmine should not fail when calling `done(true)` or `done(whatever!)`, but it's failing in my local env.

Do you have unit tests for `done` function? You should check that `done` should not fail when passing a parameter.

`"karma-jasmine": "^0.3.6",`

**Comment by maksimr** [comment]
@NoelBroda we [don't patch jasmine](https://github.com/karma-runner/karma-jasmine/blob/master/package.json#L38). So you problem in jasmine itself, try update jasmine-core

Thanks
