### ISSUE TITLE
Karma, Jasmine, Uncaught Error: <toHaveBeenCalledTimes> : Expected a spy, but got Function without test

### ISSUE THREAD

**Issue by SegmentationPro** [karma-runner/karma-jasmine#149]
Sorry in advance for my bad english..

I am testing my application with Karma and Jasmine and I have a really strange error.

I have 9 tests and when I run tests it seems that karma finds a 10th test. And Karma returns me a Jamsine error : Uncaught Error: : Expected a spy, but got Function

That is strange is : when I launch my test in debug mode. All is good.
More strange is that I have 3 files. Error occured just when I execute 3 files at the same times. With 2 files all is good ^^ ...

Have you already seen this error?

I will give you two screens. First no debug mode. Second debug mode. And I will give you my code.

**Two screens of my IDE (No Debug and Debug)**

![hlxbh](https://cloud.githubusercontent.com/assets/23629021/22291647/ba2a9e40-e307-11e6-9349-a3e12c1804ac.png)
![jw3ep](https://cloud.githubusercontent.com/assets/23629021/22291646/ba2974ac-e307-11e6-9915-8b669101c95d.png)
 

**activate.controller.js**
`    describe('userActivateCtrl', function() { 
    beforeEach(module('Betizy'));

    var $controller;
 
     beforeEach(inject(function(_$controller_, _ngToast_, _$filter_, _userService_, _navigationService_){
        $controller = _$controller_;
        ngToast = _ngToast_;
        $filter = _$filter_;
        userService = _userService_;
        navigationService = _navigationService_;
    }));

    describe('at its launch', function () {
        it('add an info toast in the toastList to say at the user what to do.', function () {
            var controller = $controller('userActivateCtrl', {
            });
    
            expect(ngToast.messages.length).toBe(1);
            expect(ngToast.messages[0].className).toBe('info');
            expect(ngToast.messages[0].content).toBe($filter('translate')('user.activate.message'));
        })
    });

    describe('for a valid registration', function () {
        it("call method from userService when activation is called by the click on activation button.", function () {
            var fakeHttpPromise = {
                then: function () {}
            };
            var controller = $controller('userActivateCtrl', {
        });
            controller.userActivateForm = {$valid: true};
            spyOn(userService, 'activate').and.returnValue(fakeHttpPromise);
            spyOn(navigationService, 'toIndex').and.returnValue(fakeHttpPromise);

            controller.activate();

        expect(userService.activate).toHaveBeenCalledTimes(1);

        setTimeout(function () {
            expect(navigationService.toIndex).toHaveBeenCalledTimes(1);
            done();
        })
    })
    });
    
    describe('for an invalid activation form', function () {
    it("does nothing.", function () {
        var controller = $controller('userActivateCtrl', {
        });
        var fakeHttpPromise = {
            then: function () {}
        };
        controller.userActivateForm = {$valid: false};
        spyOn(userService, 'activate').and.returnValue(fakeHttpPromise);
        ngToast.dismiss();
        controller.activate();
        expect(ngToast.messages.length).toBe(0);
        expect(userService.activate).not.toHaveBeenCalled();
    })
    });
    });`

**login.controller.js**
`    describe('userLoginCtrl', function() {

    beforeEach(module('Betizy'));

    beforeEach(inject(function (_$controller_, _$stateParams_, _ngToast_, _$filter_) {
    $controller = _$controller_;
    $stateParams = _$stateParams_;
    ngToast = _ngToast_;
    $filter = _$filter_;
    }));

    describe('at its launch', function () {
    it('add an info toast in the toastList to say at the user what to do.', function () {
        var controller = $controller('userLoginCtrl', {});

        expect(ngToast.messages.length).toBe(1);
        expect(ngToast.messages[0].className).toBe('info');
        expect(ngToast.messages[0].content).toBe($filter('translate')('user.login.message'));
    });

    it('add an danger toast in the toastList if user was mistaken during authentication.', function () {
        $stateParams.state = "error";

        var controller = $controller('userLoginCtrl', {});
        expect(ngToast.messages.length).toBe(2);
        expect(ngToast.messages[0].className).toBe('danger');
        expect(ngToast.messages[0].content).toBe($filter('translate')('user.login.error'));
    });
    });
    });`

**register.controller.js**
`    describe('userRegisterCtrl', function(){
    beforeEach(module('Betizy'));

    var $controller;

    beforeEach(inject(function(_$controller_, _userService_, _ngToast_, _$filter_, _navigationService_){
    $controller = _$controller_;
    userService = _userService_;
    ngToast = _ngToast_;
    $filter = _$filter_;
    navigationService = _navigationService_;
    }));

    describe('at its launch', function () {
       it('add an info toast in the toastList to say at the user what to do.', function () {
       var controller = $controller('userRegisterCtrl', {
       });

       expect(ngToast.messages.length).toBe(1);
       expect(ngToast.messages[0].className).toBe('info');
       expect(ngToast.messages[0].content).toBe($filter('translate')('user.register.message'));
   })
    });

    describe('for a valid registration', function () {
    it("call method from userService when register is called by the click on register button.", function () {
        var fakeHttpPromise = {
            then: function () {}
        };
        var controller = $controller('userRegisterCtrl', {
        });
        controller.userRegisterForm = {$valid: true};
        spyOn(userService, 'register').and.returnValue(fakeHttpPromise);
        spyOn(navigationService, 'toIndex').and.returnValue(fakeHttpPromise);

        controller.register();

        expect(userService.register).toHaveBeenCalledTimes(1);

        setTimeout(function () {
            expect(navigationService.toIndex).toHaveBeenCalledTimes(1);
            done();
        })
    })
    });

    describe('for an invalid registration with invalid mail adress', function () {
    it("add a danger toast in the toastList for an incorrect mail adress pattern.", function () {
        var controller = $controller('userRegisterCtrl', {
        });
        controller.userRegisterForm = {$error: {email: true}, $valid: false};
        ngToast.dismiss();
        controller.register();
        expect(ngToast.messages.length).toBe(1);
        expect(ngToast.messages[0].className).toBe('danger');
        expect(ngToast.messages[0].content).toBe($filter('translate')('user.register.error.email.pattern'));
    })
    });

    describe('for an invalid registration and a valid mail adress', function () {
    it("does nothing.", function () {
        var controller = $controller('userRegisterCtrl', {
        });
        var fakeHttpPromise = {
            then: function () {}
        };
        controller.userRegisterForm = {$error: {email: false}, $valid: false};
        spyOn(userService, 'register').and.returnValue(fakeHttpPromise);
        ngToast.dismiss();
        controller.register();
        expect(ngToast.messages.length).toBe(0);
        expect(userService.register).not.toHaveBeenCalled();
    })
    });
    });`

Thank you in advance ! :)

**Comment by maksimr** [comment]
@SegmentationPro do you have same error if run karma from console?

```sh
karma start
```

Thanks

**Comment by SegmentationPro** [comment]
I will try this night.

To complement my issue I complete it.

EDIT : 1 When I debug in chrome with inspector I see that :

    SUCCESS userActivateCtrl for a valid registration call method from userService when activation is called by the click on activation button.

And just after I see that :

    Uncaught Error: : Expected a spy, but got Function. Usage: expect().toHaveBeenCalledTimes() at compare (jasmine.js:3302) at Expectation.toHaveBeenCalledTimes (jasmine.js:1543) at activate.controller.js:41


So question is why it executes that whereas test passed just before?

**Comment by SegmentationPro** [comment]
I tried karma start but problem persists.

Have you an other idea?

**Comment by peteringram0** [comment]
I have stated getting this exact problem. My tests complete then at the end i get.

````
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: <toHaveBeenCalledWith> : Expected a spy, but got Function.
  Usage: expect(<spyObj>).toHaveBeenCalledWith(...arguments)
  at jasmine-core/jasmine.js:3340

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 47 of 78 ERROR (2.86 secs / 2.835 secs)
````

**Comment by maksimr** [comment]
@SegmentationPro @peteringram0 It will be great if you create test project with this problem.

Because It's look like a problem of test code, not karma, karma-jasmine or jasmine-core

Thanks
