### ISSUE TITLE
Karma runner/Jasmine 2.0

### ISSUE THREAD

**Issue by maximedupre** [karma-runner/karma-jasmine#15]
Hello, hopefully this is the right place to post. I was wondering when Jasmine 2.0 will be available with karma (karma-jasmine). I like how jasmine tests async functions in 2.0, but currently there is no way for me to use Jasmine 2.0 (or is there?).

Thank you!

**Comment by ohjames** [comment]
It seems really weird to me to have to get an older version of karma-jasmine to get a newer version of jasmine, jasmine 1's ability to test asynchronous code is pretty poor.

**Comment by dignifiedquire** [comment]
@ohjames this is not true anymore, the current release of karma-jasmine is fully compatible with jasmine 2

**Comment by ohjames** [comment]
Weird, I was on karma-jasmine 1.0.2 and seemed to lack `done`, until I downgraded to 0.2.2. Using some ancient version of node/npm on a client system, maybe some bug or stupid mistake.

**Comment by dignifiedquire** [comment]
@ohjames you need to install `jasmine-core` manually https://github.com/karma-runner/karma-jasmine#jasmine-20-docs that might have been the issue
