### ISSUE TITLE
Detail message not helpful

### ISSUE THREAD

**Issue by roopkt** [karma-runner/karma-jasmine#152]
JASMINE 2.4.1
expect(someValue).toBe(otherValue);
It does not show the detail message. 

Currently, it just says **expected false to be true** and it spits out bunch of file references like below:

> buildExpectationResult@file:/// ..., expectationResultFactory@file:... , addExpectationResult@file:///C:/Users/, addExpectationResult@file://... in ..file (line 52)

I think it should  just show that test case failed message and why it failed. I am not sure why it is  showing other 3 files names and its locaitons ?

**Comment by maksimr** [comment]
@roopkt if [jasmine](https://github.com/jasmine/jasmine) support it, then karma also should support this option.

**Comment by roopkt** [comment]
Sorry I should have posted in jasmine thread.
