### ISSUE TITLE
Exceptions in afterAll are not handled

### ISSUE THREAD

**Issue by TheModMaker** [karma-runner/karma-jasmine#161]
An exception thrown in an `afterAll` callback do not result in failed tests (or any failure).  Similarly, the `fail` method has no effect when called within an `afterAll`, whether synchronous or asynchronous.  Both an exception thrown and `fail` result in failure when using the default (standalone) jasmine launcher.

```js
afterAll(function() {
  throw 1;
});

it('should fail', function() {
  expect(true).toBe(true);
});
```

**Comment by maksimr** [comment]
@TheModMaker [jasmine](https://github.com/jasmine/jasmine) is the better place for this issue :)

Thanks!

**Comment by TheModMaker** [comment]
It works as expected in the [jasmine npm module](https://www.npmjs.com/package/jasmine).  It doesn't work when run in karma.

**Comment by maksimr** [comment]
@TheModMaker ok I got it
