### ISSUE TITLE
Angular2 - KarmaJS - unit Tests no executed automatically on npm test

### ISSUE THREAD

**Issue by dalidovski** [karma-runner/karma-jasmine#166]
# Dependencies versions

"karma": "^1.2.0"
"karma-chrome-launcher": "^2.0.0"
"karma-cli": "^1.0.1"
"karma-jasmine": "1.0.2"

# Description

I'm using KarmaJS and JasmineJS for unit testing on Angular2. When I run "npm test" the browser opened automatically, however the tests not executed automatically.

![ng-test](https://cloud.githubusercontent.com/assets/22326523/24695660/e65c17e4-19e6-11e7-99a7-aa4b358ef7d3.png)

If I change any file all the tests will be executed in the project.

![ng-test-success](https://cloud.githubusercontent.com/assets/22326523/24695659/e65b9620-19e6-11e7-8ba8-3621b8933f64.png)

Here is my Karma-conf.js

![karma-conf](https://cloud.githubusercontent.com/assets/22326523/24695661/e65daf1e-19e6-11e7-9482-0ce5a3e52612.png)

Here is my test.ts

![test-ts](https://cloud.githubusercontent.com/assets/22326523/24695662/e65e9618-19e6-11e7-8485-6620f5eadebf.png)

**Comment by maksimr** [comment]
Duplicate https://github.com/karma-runner/karma/issues/2646
