### ISSUE TITLE
Asynchronous support?

### ISSUE THREAD

**Issue by juanca** [karma-runner/karma-jasmine#185]
Not really sure how to figure out what is at fault but I figured this might be a decent spot to ask for advice:

This is the test file:

```
it('fails on purpose', function() {
  console.log('Expected failure');
  expect(true).toEqual(false);
});

it('fails without purpose (asynchronously)', function(done) {
  console.log('Unexpected failure');
  expect(true).toEqual(true);
  done();
});
```

### Expected behaviour

1 failure, 1 success

### Actual behaviour

2 failures, 0 success

with the following report:

```
18:28:11.675 spec.js:2 Expected failure
18:28:11.684 debug.js:15 FAILED  fails on purpose
18:28:11.684 spec.js:7 Unexpected failure
18:28:11.687 debug.js:21 Uncaught Expected true to equal false.
    at Object.<anonymous> (http://localhost:9876/base/spec.js:3:16)
(anonymous) @ debug.js:21
18:28:11.687 debug.js:15 FAILED  fails without purpose (asynchronously)
18:28:11.687 debug.js:6 Skipped 0 tests
18:28:11.688 debug.js:21 Uncaught Uncaught Expected true to equal false.
    at Object.<anonymous> (http://localhost:9876/base/spec.js:3:16) thrown
(anonymous) @ debug.js:21
```

### Environment Details

- webpack@2.5.0
- karma@1.7.0
- jasmine@2.7.0
- karma-webpack@2.0.4
- karma-jasmine@1.1.0

===

Jasmine keeps catching the thrown exception on all async specs. :( I'm not really sure if `debug.js` is set up correctly for asynchronous specs. 

If I had multiple asynchronous spec, each would throw the previous uncaught exception.

**Comment by daanstolp** [comment]
I just posted the exact same thing as an [issue on the karma github](https://github.com/karma-runner/karma/issues/2811). I'm not quite sure if it is specific to karma or to the karma-jasmine plugin. Have you had any luck finding a fix or workaround?

**Comment by juanca** [comment]
I have not found a fix for this -- besides getting the specs green 😺 

😭

**Comment by maksimr** [comment]
@juanca @daanstolp could you provide gist which reproduces this problem

Thanks

**Comment by juanca** [comment]
Yeah, it does work without karma. 

I'll post steps tomorrow since I'm not near a working computer today.

**Comment by daanstolp** [comment]
Hi @maksimr, see my previous comment with the link to the karma issue. It describes the exact steps to reproduce. The main culprit is the Debug.js file of the karma debug runner.

**Comment by juanca** [comment]
Finally on a working computer, will try to get a public repo setup by EOD. 

Something I want to capture before it leaves my head: I'll mess around with the iframe options in Karma in case that is correlated with our issues.

**Comment by juanca** [comment]
Repo set up @ https://github.com/juanca/karma-jasmine-async-bug

README contains SHAs which showcase how it works with just `jasmine` and how it works and does not work with `karma`/`karma-jasmine`. 

Let me know if y'all need anything else.

**Comment by daanstolp** [comment]
As I mentioned before, this issue is not particular to Jasmine, but can be traced to the Debug.js file of the karma debug runner. I have published a pull request with a fix, which has just now been accepted and merged into master. See [the issue here](https://github.com/karma-runner/karma/issues/2811) and the [pull request here](https://github.com/karma-runner/karma/pull/2817).

**Comment by juanca** [comment]
Awesome work! Thank you for the fix!
