### ISSUE TITLE
Can't find a way to pass Jasmine helper file path from Karma config?

### ISSUE THREAD

**Issue by josh08h** [karma-runner/karma-jasmine#189]
I am trying to run a file before my tests run in order to initialise an [Enzyme adapter](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md)
```
module.exports = function(config) {
  config.set({
    client: {
      jasmine: {
        helpers: ['path/to/helper.js']
      }
    }
  })
}
```
Is something like this possible?

**Comment by joejuzl** [comment]
Or a way to specify the jasmine config file location i.e 
```
client: {
  jasmine: {
    config: ['path/to/jasmine.json']
  }
}
```
Then you can specify the helpers in there.
Read: https://github.com/jasmine/jasmine-npm/commit/80e6b334d424202893519e6900568c65a663db40

**Comment by maksimr** [comment]
@josh08h you could put *helper.js* as a first file in `config.files`

```js
files: ['path/to/helper.js', 'path/to/src.js']
```
