### ISSUE TITLE
Get "... implements __karma__.start method!" error after adding static assets

### ISSUE THREAD

**Issue by rts-cwalker** [karma-runner/karma-jasmine#190]
See my test repo here: https://github.com/rts-cwalker/angular-karma-test

`karma-jasmine` version 1.1.0

I can run `ng test` perfectly fine before I add all of static assets into the `src/assets` folder. But once I add all of my assets to that folder and run `ng test` again, it fails with the error `You need to include some adapter that implements __karma__.start method!`

I have had issues with this error, so i created a brand new Angular project and after adding the files from each directory from my previous project, i reran `ng test` each time. And after i added the assets, it failed. I deleted all the assets, and `ng test` ran fine again. Add assets back, and it fails again.

It doesnt occur when I add just a few files. It works fine when i add a few other files in `src/assets` such as `robots.txt`, `browserconfig.xml`, `humans.txt`, etc. Im not totally sure where the problem lies. I can also the `css` folder without getting the error, but any other subdirectory under `src/assets` throws the error (`js/`, `media/`, `fonts/`, etc. Either separately or together it throws the error)

**Comment by rts-cwalker** [comment]
Update: I at least have the tests running again by adding `exclude: ['src/assets/*/**']` to my config file. But not sure as of yet how this will affect anything in the future

**Comment by maksimr** [comment]
@rts-cwalker could you open *localhost:9876/debug.html* and look at the console.

**Comment by rts-cwalker** [comment]
@maksimr I have done that. Here is what i get for that:

**Comment by rts-cwalker** [comment]
@maksimr here are the errors:
`adapter.js:304 Uncaught TypeError: Cannot read property 'args' of undefined
    at Object.filterString (adapter.js:304)
    at new KarmaSpecFilter (adapter.js:289)
    at createSpecFilter (adapter.js:302)
    at adapter.js:392
    at adapter.js:395`

and 

`context.js:257 Uncaught TypeError: Cannot read property 'error' of undefined
    at directCallParentKarmaMethod (context.js:257)
    at ContextKarma.error (context.js:150)
    at ContextKarma.UNIMPLEMENTED_START [as start] (context.js:156)
    at Object.../../../../../src/test.ts (_karma_webpack_/webpack:/Users/rockytopsolutions/development/rockytopsolutions/itemfinder/src/test.ts:32)
    at __webpack_require__ (_karma_webpack_/webpack:/webpack/bootstrap ee4ffe316269033c7786:54)
    at webpackJsonpCallback (_karma_webpack_/webpack:/webpack/bootstrap ee4ffe316269033c7786:25)
    at main.bundle.js:1`

**Comment by maksimr** [comment]
@rts-cwalker Thanks

> adapter.js:304 Uncaught TypeError: Cannot read property 'args' of undefined at Object.filterString (adapter.js:304) at new KarmaSpecFilter (adapter.js:289) at createSpecFilter (adapter.js:302) at adapter.js:392 at adapter.js:395 at adapter.js:304

This means that something wrong with `window.__karma__.config`. `window.__karma__.config` always should be defined.

> context.js:257 Uncaught TypeError: Cannot read property 'error' of undefined at directCallParentKarmaMethod (context.js:257) at ContextKarma.error (context.js:150) at ContextKarma.UNIMPLEMENTED_START [as start] (context.js:156) at Object.../../../../../src/test.ts 

This exception appears because previous error prevent initialization of karma-jasmine adapter 

> Uncaught SyntaxError: Invalid or unexpected token at debug.html:44

This is interesting, maybe this exception prevent to set `window.__karma__.config`.
Could you debug this error?

Thanks

**Comment by rts-cwalker** [comment]
Sorry For a delay. Been a busy few weeks. I can try to start looking into this here soon
