### ISSUE TITLE
 TypeError: Cannot read property 'run' of null

### ISSUE THREAD

**Issue by asborker** [karma-runner/karma-jasmine#195]
Chrome 64.0.3282 (Windows 10.0.0) AppComponent should create the app FAILED
        TypeError: Cannot read property 'run' of null
            at <Jasmine>
            at UserContext.<anonymous> node_modules/zone.js/dist/jasmine-patch.js:106:1)
            at <Jasmine>
            at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask node_modules/zone.js/dist/zone.js:421:1)
            at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask node_modules/zone.js/dist/zone.js:188:1)
            at drainMicroTaskQueue node_modules/zone.js/dist/zone.js:595:1)
            at <Jasmine>
        TypeError: Cannot read property 'run' of null
            at <Jasmine>
            at UserContext.<anonymous> node_modules/zone.js/dist/jasmine-patch.js:106:1)
            at <Jasmine>
            at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask node_modules/zone.js/dist/zone.js:421:1)
            at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask node_modules/zone.js/dist/zone.js:188:1)
            at drainMicroTaskQueue node_modules/zone.js/dist/zone.js:595:1)
            at <Jasmine>
        TypeError: Cannot read property 'run' of null
            at <Jasmine>
            at UserContext.<anonymous> node_modules/zone.js/dist/jasmine-patch.js:104:1)
            at <Jasmine>
            at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask node_modules/zone.js/dist/zone.js:421:1)
            at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask node_modules/zone.js/dist/zone.js:188:1)
            at drainMicroTaskQueue node_modules/zone.js/dist/zone.js:595:1)
            at <Jasmine>

**Comment by rfprod** [comment]
@asborker are you using karma-jasmine 1.1.1 with jasmine-core 3.1.0 ?
if it is so, downgrade jasmine-core to 2.99.1 and try again

**Comment by monominia** [comment]
I also have the same question. But, I only used Jasmine in the testing of an Angular service. The method by @rfprod should be a good fit because my service does not need the browser. In the meantime, the method by @dstj  also does not work. I feel depressed on the error.

**Comment by rfprod** [comment]
@monominia 
actually, this setup works, tried it after @dstj 's tip
...
"jasmine-core": "^3.1.0",
"zone.js": "^0.8.21"
...

**Comment by monominia** [comment]
@rfprod 
Thanks for your help, I have fixed this issue.
