### ISSUE TITLE
Time is always reported as `NaN`

### ISSUE THREAD

**Issue by nicojs** [karma-runner/karma-jasmine#196]
The time reporting is broken since a change done in Jasmine in October of last year. 

The way time reporting works now is:

```js
  this.specStarted = function (specResult) {
    specResult.startTime = new _Date().getTime()
  }

  this.specDone = function (specResult) {
    var skipped = specResult.status === 'disabled' || specResult.status === 'pending'

    var result = {
        // ...
        time: skipped ? 0 : new _Date().getTime() - specResult.startTime,
    }
}
```

However, the arguments of reporters are cloned from the original since this commit: https://github.com/jasmine/jasmine/commit/1f6c91de7ce788126ac59040bc803b22acbbab58#diff-0aba87f0f765b8ab7c25d0aa59530ed2

Thus the `specResult` object is not the same anymore, `specResult.startTime` is always `undefined`, thus the `time` will be `NaN`.

I think the first release with this change was 2.9

**Comment by nicojs** [comment]
@slackersoft shouldn't this have been reported as a breaking release? It is reported as "Issue" in the changelog: https://github.com/jasmine/jasmine/blob/master/release_notes/2.9.0.md

**Comment by slackersoft** [comment]
I would be inclined to look at the fact that Jasmine previously used the same actual object as the `result` as a implementation detail of Jasmine and as such, not defined functionality. This means we can make changes for better interoperability (as that PR was) of other libraries that might depend on Jasmine.

As a side note, next time you have an issue you'd like to bring up with the Jasmine team, please don't just @ a single maintainer in an unrelated repository, but create a new issue in an appropriate Jasmine repository. This way you ensure that you concern can be viewed with more Jasmine context, and in the case that the person you select isn't available.
