### ISSUE TITLE
expectAsync will not work with angularJS promises.

### ISSUE THREAD

**Issue by codymikol** [karma-runner/karma-jasmine#220]
When attempting to use the expectAsync feature of jasmine ex.

```javascript
await expectAsync($q.resolve('RESULT')).toBeResolvedTo('RESULT');
```

You will always receive the error "Expected expectAsync to be called with a promise."

This is because Jasmine pipes the passed promise to this isPromise method which checks that the promise has the global / window Promise constructor.

```javascript
j$.isPromise = function(obj) {
  return typeof jasmineGlobal.Promise !== 'undefined' && obj && obj.constructor === jasmineGlobal.Promise;
};
```

This will return false because the angularJS implementation of Promise has a different constructor than the jasmineGlobal.Promise

We should be able to fix this by ensuring this comparison is overridden by the angularJS angular.isPromiseLike method.

This is my first issue on this project. I'm going to try to write some tests that catch this and fix the issue, but if I can't manage it, I figured I would at least dump as much information as I have here.

**Comment by johnjbarton** [comment]
> because the angularJS implementation of Promise has a different constructor than the jasmineGlobal.Promise

Seems like this is an issue that angularJS should solve.

**Comment by codymikol** [comment]
Hello, I'm going to close this out. This is something that I am fixing in jasmine itself tracked over [here](https://github.com/jasmine/jasmine/pull/1613). Sorry for the confusion!
