### ISSUE TITLE
Focused tests don't lead to an incomplete test run

### ISSUE THREAD

**Issue by heiin** [karma-runner/karma-jasmine#225]
Since jasmine 3.0.0 the test run is incomplete and fails if focused tests (fit or fdescribe) are found.
If I run the tests with karma the test run still has the old behaviour of succeeding.

The Issue can be reproduced by creating a new project with the following package.json
```
{
    "name": "karma-jasmine-test",
    "version": "1.0.0",
    "description": "",
    "dependencies": {
        "jasmine": "3.3.0",
        "jasmine-core": "3.3.0",
        "karma": "3.1.1",
        "karma-chrome-launcher": "2.2.0",
        "karma-jasmine": "1.1.2"
    },
    "devDependencies": {},
    "scripts": {
        "test": "karma start",
        "jasmine-test": "jasmine"
    }
}
```
Then create two tests, a focused and a normal one. The karma run succeeds while the jasmine run fails.

Maybe there could be a config parameter that controls the behaviour so you can use focused test in development and also make sure they don't make it to the repository.

Thanks.

**Comment by heiin** [comment]
Maybe someone can confirm that this is not intended behaviour and a problem with karma-jasmine (not with karma itself)? I could try to create a solution myself and make a pull-request.

**Comment by heiin** [comment]
Thanks for the response. 
I can see that this would be a breaking change (as it is for jasmine). We use the kjhtml reporter in our project (more or less the standard angular configuration). Should I open an issue there? If the jasmine events land there, the reporter should have the needed information.
I thought the reporter was only a means to visually display the test results in some way.

**Comment by johnjbarton** [comment]
Architecturally the most flexible solution is to write a test `exit-reporter` that monitors the results and takes whatever action you want.  It's a simple plugin to write. 

Since karma is a server rather than a one-shot process, the handling of exit is more complex than it is in jasmine. Different users may have different requirements.  

Finally, the jasmine-specific feature handling belongs in karma-jasmine at least.  It's not something the core runner should handle, though we might need some additional generic support for exit codes.

**Comment by heiin** [comment]
Okay, I wrote a very basic plugin that closes the Test run if Tests are skipped.

Really appreciate the help.

**Comment by BevanR** [comment]
@heiin Could you share your plugin or some advice for how to get started with such a plugin?

**Comment by BevanR** [comment]
Also, I found https://www.npmjs.com/package/no-skipped-tests

**Comment by heiin** [comment]
The package you posted looks a bit overengineered to me for the task.
What i did was create the plugin itself in its own file like this: 

```
const exitReporter = function(config) {
    this.onBrowserComplete = function(browser) {

        const result = browser.lastResult;
        if (result.skipped && config.singleRun) throw new Error("Tests skipped!");
    };
};

exitReporter.$inject = ["config"];

module.exports = {
    "reporter:exit": ["type", exitReporter]
};
```
I used the condition config.singleRun because that is the way it is used in the automatic build process so you can still use focused tests in "infinite" mode.

Now you can use the plugin via the karma.conf.js. Require it in the plugin section per `require("./<file-name-of-the-plugin>")` and add the name of the plugin (I named it exit - naming is hard) in the reporters array.

I don't remember where I found a good documentation on writing own plugins, but http://karma-runner.github.io/4.0/dev/plugins.html could be a starting point.

I hope this helps and I forgot nothing.

**Comment by BevanR** [comment]
Awesome. Thanks!

I created https://www.npmjs.com/package/karma-skipped-tests-reporter as a starting point for future collaboration on this.
