### ISSUE TITLE
specFilter deprecation warning, although it's not used

### ISSUE THREAD

**Issue by pmattke** [karma-runner/karma-jasmine#227]
I have an Angular 7 project, and just upgraded the package.json to the latest versions of all dependencies. I wanted to verify that everything still works, and executing the unit tests, I get the following deprecation warning:

```
DEPRECATION: Setting specFilter directly on Env is deprecated, please use the specFilter option in `configure`
```

The tests succeed as normal.

The warning irritates me since I don't use `specFilter` anywhere in the project - at least not explicitely. Nor do I know, what this property exactly does.

Can someone help me out here?

**Comment by johnjbarton** [comment]
See #221
