### ISSUE TITLE
test suite loops forever

### ISSUE THREAD

**Issue by iosonomarcop** [karma-runner/karma-jasmine#230]
Hi all,
updated to karma-jasmine 2.0.1 and after that runner keeps executing the tests in a loop (the process never ends). As you can see from the attached screenshot I have 3242 tests but the runner has already executed 3689 (and it keeps going).
![screenshot 2018-11-26 at 16 45 26](https://user-images.githubusercontent.com/41512723/49026048-310e9980-f19d-11e8-88d0-faa816944ea9.png)

with karma-jasmine 2.0.1 I'm using:
- jasmine-core 3.3.0
- karma 3.1.0
- karma-chrome-launcher 2.2.0
- karma-cli 1.0.1

Everything worked file with:
- jasmine-core 2.99.1
- karma-jasmine 1.1.2
- karma 3.1.0
- karma-chrome-launcher 2.2.0
- karma-cli 1.0.1

node version 10.13.0 (for both)

anybody knows what the problem might be?

**Comment by johnjbarton** [comment]
Try using the no-single-run option, 
https://github.com/karma-runner/karma/blob/79f7fe40fbcd498134eb048370bd2824a87dbfc1/docs/intro/05-troubleshooting.md
to open devtools to investigate. It almost has to be something in your test code that is calling jasmine `describe()` or `it()` which then calls your test code, etc.

**Comment by iosonomarcop** [comment]
I did but I don't see anything that looks like an error to me. Here the screenshot of the log (white stripes are there to hide the local machine path)
![screenshot 2018-11-27 at 14 49 16](https://user-images.githubusercontent.com/41512723/49086424-c4ef6c80-f254-11e8-8334-20e5de9c64b8.png)

it keeps fetching _runtime.js_, _polyfills.js_ etc.. and I don't understand why, but that's out of my control.
I don't know if matters but I'm using angular 7.

**Comment by johnjbarton** [comment]
> it keeps fetching runtime.js, polyfills.js etc.. 

Sounds like your code is reloading the web page.  You can add a handler to your test (make sure to add it somewhere you know is executed according to the log). https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload  The handler can put up a dialog to verify that you  are reloading. 

> but that's out of my control.

This is an issue that you will need to investigate and fix.  It is not a bug in karma code, or angular for that matter.  Maybe setting breakpoints in devtools will work.   Start commenting out large sections of test or app code until you see a change.  You can do it, good luck!
