### ISSUE TITLE
Pattern ".../node_modules/karma-jasmine/lib/adapter.js" does not match any file.

### ISSUE THREAD

**Issue by limonte** [karma-runner/karma-jasmine#242]
In v3.0.0 release you probably forgot to build before the release, the same as in https://github.com/karma-runner/karma-jasmine/issues/123#issuecomment-216641634

**Comment by limonte** [comment]
How many times this issue needs to be reported before you guys realize that manual work is a bug and releasing process should be automated with `semantic-release` or any similar tool? :)

**Comment by coyoteecd** [comment]
Same here, `lib/adapter.js` file is missing from the 3.0.0 release...

**Comment by pmstss** [comment]
Having the same in output with 3.0.0:

```
05 01 2020 13:03:34.145:WARN [filelist]: Pattern "./node_modules/karma-jasmine/lib/adapter.js" does not match any file.
```

Is it the reason of getting `You need to include some adapter that implements __karma__.start method!` (works with 2.0.1)?

**Comment by wodddy** [comment]
almost 4 years ago it was just like this
https://github.com/karma-runner/karma-jasmine/issues/123#issuecomment-216641634

**Comment by fr0** [comment]
What is the workaround for this?

**Comment by johnjbarton** [comment]
Please reinstall, that should bring in 3.0.1.

**Comment by limonte** [comment]
> What is the workaround for this?

```sh
npm install --save-dev karma-jasmine@^2.0.0
```

**Comment by DamienCassou** [comment]
> Please reinstall, that should bring in 3.0.1.

thank you very much!

@limonte: when I see a sentence like the one you wrote above, I feel bad for the maintainer who is doing his/her best to provide a tool we all use. In your message I read both a piece of advice (which is good) and some critics on how the maintainer is working. I think such maintainer doesn't deserve being told s/he can't do the job properly. May I suggest you spend some more time writing this kind of messages to make sure the reader is going to appreciate the advice instead of feeling criticized?

**Comment by limonte** [comment]
@DamienCassou 

Thank you for the advice, I'm fine with being honest and not losing time for imagining what emotions people might have.

I do criticize maintainers for repeating the same mistake for 4 years and not trying to solve it. That's unprofessionally and I will tell that directly. Now, it's on them either to finally fix the issue or get offended and continue doing the same mistakes.

I have an advice to you as well, stop imagining what other people might feel :) There's the exemplary case on GitHub demonstrating what might happen if you care about feelings too much: https://github.com/microsoft/vscode/issues/87268 

Because of feelings, the VSCode's issue tracker was put down for a couple of days. Caring about feelings is often counterproductive.

Man up, brother, and nothing in this world will be able to make you feel bad.

All the best to you in 2020!

**Comment by johnjbarton** [comment]
@limonte You seem to be quite the expert. Your pull request would be the professional response to a problem that bothers you.

**Comment by simonua** [comment]
@johnjbarton, that was the best possible response. Well done. Also, thank you very much for maintaining this package. I appreciate you.

**Comment by limonte** [comment]
> @limonte You seem to be quite the expert. Your pull request would be the professional response to a problem that bothers you.

I'm not the expert by any means, but here you go: #247

**Comment by johnjbarton** [comment]
PR #247 (eventually) lead to our use of semantic release, something I hope to rollout to the rest of the karma-runner projects.  Thanks!

**Comment by lk77** [comment]
i've lost so much time with this issue
