### ISSUE TITLE
Running single test gives: AfterAll TypeError cannot read property 'info' and 'error' of undefined

### ISSUE THREAD

**Issue by elonmallin** [karma-runner/karma-jasmine#267]
It seems that running karma works but clicking on a single test in the browser gives errors.

### Reproduce:
1. `npx karma start`
2. Click the test [should test true](http://localhost:9876/context.html?spec=TestSuite%20should%20test%20true) in the jasmine output in the browser
3. See the error output below:
![image](https://user-images.githubusercontent.com/9149793/78558104-563ffd00-7812-11ea-9d45-99d8ed03b2be.png)

### My setup:
*package.json*
```json
{
  "name": "karma-test",
  "main": "index.js",
  "devDependencies": {
    "@types/jasmine": "^3.5.10",
    "jasmine-core": "^3.5.0",
    "karma": "^4.4.1",
    "karma-jasmine": "^3.1.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "jasmine-spec-reporter": "^5.0.1",
    "karma-chrome-launcher": "^3.1.0"
  }
}
```
*karma.conf.js*
```js
module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'],
    plugins: [
      require('karma-jasmine'),
      require('karma-jasmine-html-reporter'),
      require('karma-chrome-launcher'),
    ],
    client: { clearContext: false },
    files: ['*spec.js'],
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
  })
}
```
*test.spec.js*
```js
describe("TestSuite", function () {
    it("should test true", function() {
        expect(true).toBeTruthy();
    });
});
```

I've tried removing my `node_modules` directory and installing again but that doesn't work. And I am on the latest versions of all packages.

**Comment by pmo1948** [comment]
Hey,
I had a similar issue, when using ngrx. This https://github.com/ngrx/platform/issues/1546 holds that use case.
Just saying you might want to be sure your problem is really with karma

**Comment by elonmallin** [comment]
It was a while ago now but I think I narrowed it down to these three files and it's only karma and jasmine stuff that's used right? Unless it's because of some reporter plugin or so.

**Comment by johnjbarton** [comment]
>  but clicking on a single test in the browser gives errors.

That's a hint that your issue is related to the karma-jasmine-html-reporter.  That is the plugin that writes links into the page, not karma-jasmine.
