### ISSUE TITLE
New release with jasmine-core ^3.6.0

### ISSUE THREAD

**Issue by sidvishnoi** [karma-runner/karma-jasmine#274]
It has been a while since the last release. There are some nice goodies in [jasmine-core^3.6.0](https://github.com/jasmine/jasmine/blob/main/release_notes/3.6.0.md): three new matchers (`toHaveBeenCalledOnceWith`, `toHaveSize` and `toBePending`), and numerous bug fixes. Would be nice to have a new release with updated dependencies. Also, there are multiple devDependencies that can be updated.

**Comment by johnjbarton** [comment]
Please send a pull request with the new dependency.
