### ISSUE TITLE
Error: 'null' is not an object (evaluating 'currentSpec.expect')  

### ISSUE THREAD

**Issue by kwakayama** [karma-runner/karma-jasmine#37]
Hi
I'm using karma-jasmine v0.2.2.
When my test files become bigger and bigger I get the following error:

```
PhantomJS 1.9.7 (Mac OS X) ERROR  
TypeError: 'null' is not an object (evaluating 'currentSpec.expect')  
at /Users/kentarowakayama/CODE/ANGULAR/fischer/node_modules/karma-jasmine/lib/jasmine.js:698
```

**Comment by Guamaso** [comment]
Had the same problem. I was using `setTimeout` without calling `done()`. :P

**Comment by moogleberry** [comment]
I had this too; was using `inject()` in an `it()` statement without something to inject (no param)

**Comment by moslemezzati** [comment]
Thanks @moogleberry  this my problem too :laughing:
