### ISSUE TITLE
So, duplicate error messages

### ISSUE THREAD

**Issue by wizardwerdna** [karma-runner/karma-jasmine#60]
The drivers (and this may be a driver issue) working with Jasmine 1.X would result in concise assertion failure reports along the lines of: 

```bash
PhantomJS 1.9.8 (Mac OS X) ngFromHtml() should work for simple dynamic html FAILED
        Expected '' to be '2'.
PhantomJS 1.9.8 (Mac OS X): Executed 4 of 4 (1 FAILED) (0.005 secs / 0.022 secs)
```

However, under Jasmine 2.x, we get duplicated errors messages:

```bash
PhantomJS 1.9.8 (Mac OS X) ngFromHtml() should work for simple dynamic html FAILED
        Expected '' to be '2'.
        Error: Expected '' to be '2'.
            at /Users/werdna/wiz-dev-env/test/environment.js:33
            at /Users/werdna/wiz-dev-env/node_modules/karma-jasmine/lib/boot.js:126
            at /Users/werdna/wiz-dev-env/node_modules/karma-jasmine/lib/adapter.js:171
            at http://localhost:9876/karma.js:189
            at http://localhost:9876/context.html:49
```

The latter yields overlong messages and lots of undesireable cruft.

Whaddya think?  I'm happy to research this, but perhaps there is a simple and obvious solution my colleagues may provide?

**Comment by maksimr** [comment]
fixed in https://github.com/karma-runner/karma-jasmine/commit/ee4a02064f5f886bb815e5d723da34f3eca7581f

**Comment by bstenm** [comment]
Hi there, was looking at that thread, is there a good reason to return step.stack rather than step.message? In my case I get a long useless requirejs stack trace following the error message, and I'm guessing the same issue could always occur with other libs used.  I suggest that if the irrelevant stack trace is removed anyway why not always return step.message instead of adding new regex tests such as !/\/(require.js):/.test(entry)

**Comment by olegskl** [comment]
@bstenm The stack is pretty useful. It would be great though to have a configuration option that would filter out library stack traces.

**Comment by bstenm** [comment]
agreed that would be the best solution, also with a 'no-stack-trace' one would be good in which case it just returns step.message

**Comment by brachycera** [comment]
:+1: for configuration option on stack traces. 
The requireJS stack-trace make error messages difficult to read. Maybe the karma.conf "framework" option could be used to build the "framework filter"?!

**Comment by top-master** [comment]
This is not fixed yet, at least not currectly.

For example, my context contains `JSON`, which causes both the error and the JSON to get duplicated in the logs.
```js
expect(window.MyGlobalVariable)
    .withContext('Was not in global var: ' + JSON.stringify(window.jQuery, null, 2))
    .toEqual(jasmine.objectContaining({
        'my/tested/key': jasmine.objectContaining({
            default: jasmine.anything()
        })
    }));
```
