### ISSUE TITLE
xdescribe causing timeouts

### ISSUE THREAD

**Issue by stramel** [karma-runner/karma-jasmine#67]
I am updated to these versions:

**karma:** 0.12.28
**karma-jasmine:** 0.3.2
**jasmine-core:** 2.1.3

and a few reporters/preporcessors. Haven't had issues until upgrading from:

**karma:** 0.12.22
**karma-jasmine:** 0.2.2

It seems to get stuck on `xdescribe`s no matter how long the timeout period is. 

Let me know if you need more information!

**Comment by maksimr** [comment]
@stramel Thanks!

What version `karma-jasmine` you use?
It is reproduce if use `karma` without `gulp`?

**Comment by maksimr** [comment]
Can not reproduce on simple case:

```js
describe('foo', function() {
    beforeEach(function(done) {
        this.test = 'foo';
        done();
    });

    it('should be foo', function(done) {
        expect(this.test).toEqual('foo');
        done();
    });

    xdescribe('bar', function() {
        it('should be bar', function(done) {
            expect('foo').toEqual('bar');
            done();
        });
    });
});

xdescribe('zoo', function() {
    it('should be zoo', function(done) {
        expect('foo').toEqual('zoo');
        done();
    });
});
```
karma: 0.12.22
karma-jasmine: 0.2.2

**Comment by maksimr** [comment]
@stramel I close issue.

Seems it's problem of jasmine not karma-jasmine. It will be cool if you create example which reproduce problem
Feel free reopen

Thanks!

**Comment by stramel** [comment]
@maksimr yeah, sorry I got wrapped up in some other stuff. I will try to create an example.
