### ISSUE TITLE
No suites for `iit` tests

### ISSUE THREAD

**Issue by segrey** [karma-runner/karma-jasmine#68]
Let's consider this simple test:
```
describe('suite', function () {
    iit('spec', function () {
        expect(1).toBe(1);
    });
});
```

The problem is that `onSpecComplete(browser, result)` is called with empty `result.suite`.
As a result `Jump To Source` action (from right-click menu on a test tree node) in WebStorm Karma integration doesn't work.

Also `ddescribe` cuts upper suites:
```
describe('suite', function () {
    ddescribe('sub-suite', function () {
        it('spec', function () {
            expect(1).toBe(1);
        });
    });
});
```

Here `onSpecComplete(browser, result)` is called with `result` equals to
```
{
  description: 'spec',
  suites: ['sub-suite'],
  ...
}
```

**Comment by maksimr** [comment]
@segrey what about karma-jasmine@0.3.5

I try reproduce on latest version of karma-jasmine and all work fine.
Note: In new version of karma we use jasmine as dependency and jasmine@2.0 has `fit` which replace `iit`

Thanks

**Comment by segrey** [comment]
Confirming, `fdescribe` and `fit` work correctly.
