### ISSUE TITLE
Regression: no ddescribe/iit

### ISSUE THREAD

**Issue by mzgol** [karma-runner/karma-jasmine#73]
karma-jasmine 0.3.3 and 0.3.4 doesn't support `ddescribe` and `iit`. karma-jasmine 0.3.2 does. Looking at the commit queue, the `lib/boot.js` file has been completele reorganized between 0.3.2 & 0.3.3, changing API in the process (https://github.com/karma-runner/karma-jasmine/commit/207018b83201b2b72cb14a8c6d528ac24d53f7a9). Such things shouldn't happen in a patch release, it's a breaking change.

0.3.3 should really be 0.4.0. Could you release 0.3.5 that is a re-release of 0.3.2 and bump 0.3.4 master to 0.4.0? Otherwise people that include `"karma-jasmine": "~0.3.2"` may now have their builds broken.

**Comment by kenwarner** [comment]
seeing the same problem here +1

**Comment by colinkahn** [comment]
Same here.

**Comment by arty-name** [comment]
[The official Jasmine syntax now is `fit`/`fdescribe`](http://jasmine.github.io/2.1/focused_specs.html)

But it's still a breaking change.

**Comment by maksimr** [comment]
I don't think that we should to do so much manipulation for `ddescribe` and `iit`(It's more debugging features). Yup It's annoying but it force move to official API and to reduce the amount of custom code.

Thanks!

**Comment by mzgol** [comment]
> I don't think that we should to do so much manipulation for ddescribe and iit

Sure but IMO it'd be better to publish the change as 0.4.0, not 0.3.3. I guess if you considered `ddescribe` not a part of a public API, it's all fine according to semver, though, as you see, quite unexpected by others.

**Comment by jberube** [comment]
It probably is possible to circumvent the problem (if it's a problem) by doing this in the index.html file, before loading your spec files (of in you karma.conf file, or whatever you use to start your tests) :
```javascript
var ddescribe = fdescribe, iit = fit;
```

**Comment by eddiemonge** [comment]
yeah this was a breaking change that took awhile to troubleshoot. wished it was pushed to 0.4.0 like @mzgol said

**Comment by pkozlowski-opensource** [comment]
Yeh, this is pretty annoying... Can't we re-map those as suggested by @jberube ?

**Comment by jamestalmage** [comment]
As an alternative to remapping, how about this: 

```javascript
if ('undefined' === typeof window.iit) {
  window.iit = function() {
    throw new Error('"iit" is deprecated in favor of the official Jasmine API: use "fit" instead.');
  };
}
```

or something similar. At least that would put people on the right track more quickly.

**Comment by allenmanning** [comment]
It would have been sweet if I could have seen an error message like 'ddescribe is now fdescribe.' rather than go digging in node_modules to figure it out.
