### ISSUE TITLE
Tests start executing before page is loaded

### ISSUE THREAD

**Issue by astoilkov** [karma-runner/karma-jasmine#77]
I am using karma-jasmine: 0.3.5. I have tests that run perfectly from a HTML runner that loads jasmine 2.2 but when I run them through karma using karma-jasmine they fail. I have investigated the problem and it seems that the tests start executing before the DOM is ready (which is not the case when run from a HTML runner). After updating the createStartFn function in the adapter.js file to the code below which waits for the DOM ready the tests started passsing.
```javascript
function createStartFn(karma, jasmineEnv) {
  // This function will be assigned to `window.__karma__.start`:
  return function () {
    $(function () {
      jasmineEnv = jasmineEnv || window.jasmine.getEnv();

      jasmineEnv.addReporter(new KarmaReporter(karma, jasmineEnv));
      jasmineEnv.execute();
    });
  };
}
```

**Comment by tiandavis** [comment]
+1 Please investigate this. I've validated this very same issue.

**Comment by maksimr** [comment]
@astoilkov yup, You are right. Tests start before DOM is completed, but it's not issue of karma-jasmine, it is issue of karma. Because [karma call start](https://github.com/karma-runner/karma/blob/master/static/context.html#L31-L33) function.

As workaround you can create file `jasmine-global.js` which contain code:

```js
window.__karma__.start = (function(originalStartFn){
return function(){
   var args = arguments
   $(function(){
          originalStartFn.apply(null, args);
    });
};
}(window.__karma__.start));
```

Thanks!

**Comment by Flame2957** [comment]
I have this issue, the solution @maksimr posted doesn't work for me
