### ISSUE TITLE
Multi-line error messages are rendered in a weird order

### ISSUE THREAD

**Issue by 4kochi** [karma-runner/karma-jasmine#79]
Try this:

    expect('Hello\nWorld').toBe(0);

The displayed error message is:

```
FAILED TESTS:
  myTest
    myOtherTest
      ✖ should work
        PhantomJS 1.9.8 (Mac OS X)
      World' to be 0.
      Error: Expected 'Hello
          at /var/folders/(...)/blablabla-test.js:126:0
```

The problem is that in the function `getRelevantStackFrom(stack)` the stack is splitted by `\n`and when the stack also contains the error message the output is formatted wrong in the function `formatFailedStep(step)`

**Comment by maksimr** [comment]
fixed https://github.com/karma-runner/karma-jasmine/pull/86
