### ISSUE TITLE
TypeError: relevantStack[0] is undefined

### ISSUE THREAD

**Issue by sdcoca** [karma-runner/karma-jasmine#80]
Line 83 of adapter.js does not check the length of relevantStack and causes the test to fail. Adding the check as below, fixes the issue but I am unsure whether that's what you would expect:

```Javascript
if (relevantStack[0] && relevantStack[0].indexOf(step.message) !== -1) {
```

Cheers,
Sergio.

**Comment by maksimr** [comment]
@sdcoca Thanks

Can you post use case for this bug

**Comment by sdcoca** [comment]
I saw this other project having the same error:

https://travis-ci.org/sofa/sofa-pages-service

In my case it would take a while to reproduce again, but I'll let you know. It happens with focused execution.

Cheers,
Sergio.

**Comment by loki2302** [comment]
I've just faced the same behavior with a funny code like this:
```javascript
it('should blablabla', function($route) { // injecting the $route, right? :-)
  // this code does not use the $route, 
  // otherwise it would fail more nicely
});
```
It fails with "Error: Timeout - Async callback was not invoked within timeout..." in Chrome, and with "TypeError: relevantStack[0] is undefined" in Firefox.

**Comment by maksimr** [comment]
@sdcoca @loki2302 Thanks guys! We should fix it

**Comment by AndrewRevinsky** [comment]
@maksimr , when do you estimate this to get fixed? I've run into this same issue just now.

**Comment by felixcollins** [comment]
Is there a work around?

**Comment by maksimr** [comment]
Fixed in https://github.com/karma-runner/karma-jasmine/pull/85
