### ISSUE TITLE
Specify jasmine options

### ISSUE THREAD

**Issue by johannesjo** [karma-runner/karma-jasmine#81]
I really would like to add a global beforeEach to my tests. It seems to me, there this the option to set a spec_helpers.js in Vanilla jasmine. Is there any way specify such an option via the karma config?

**Comment by johannesjo** [comment]
Nevermind. Seems like a non wrapped beforeEach in one of the files just works as good.

**Comment by maksimr** [comment]
You can create file jasmine-global.js and put it first in `files` property:

karma.conf.js
```js
files: ['jasmine-global.js', ...]
```

jasmine-global.js
```js
// Global before each
beforeEach(function(){ ....});
```

Thanks

On 20 March 2015 at 15:59, Johannes Millan <notifications@github.com> wrote:

> Nevermind. Seems like a non wrapped beforeEach in one of the files just
> works as good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/karma-runner/karma-jasmine/issues/81#issuecomment-84006640>
> .
>



-- 

*Ryzhikov Maksim*

Maksim.Ryzhikov@jetbrains.com

'
