### ISSUE TITLE
Can't find variable: runs

### ISSUE THREAD

**Issue by emascarinas** [karma-runner/karma-jasmine#82]
```js
it()
...
runs(function () {
            flag = false;
            value = 0;
            setTimeout(function () {
                value++;
                //keep returning false…
                flag = false;
            }, 500);
        });

...
```

on my package.json
```json
"jasmine-core": "^2.2.0",
"karma-jasmine": "^0.3.5",
```
Do I still need to include jasmine-core?

**Comment by maksimr** [comment]
@emascarinas what means function `runs`?

**Comment by emascarinas** [comment]
Do we still need to include jasmine core separately to make use of runs and
waitFor that jsamine supports? When we use those build in jasmine methods
it errors out.

**Comment by maksimr** [comment]
@emascarinas 

npm contains only jasmine version 2.x (`npm info jasmine-core`)
If you want use jasmine 1.x you should use `karma-jasmine@0.1.x` which shipped with patched jasmine
