### ISSUE TITLE
code coverage data per spec

### ISSUE THREAD

**Issue by Malkiz** [karma-runner/karma-jasmine#83]
currently the code coverage data is sent only on jasmineDone
https://github.com/karma-runner/karma-jasmine/blob/master/src/adapter.js#L178

I want to be able to get coverage data per spec.

The use case:
On a continuous integration server, I want to match each failed spec's coverage data with the files that were changed in the commit, and thus produce better error messages for developers.

**Comment by maksimr** [comment]
@Malkiz Thanks

Really I can not fully understand profit of this feature.
You can add custom reporter to jasmine and send to karma coverage data on `suiteStarted` or `suiteDone`:

```js
window.jasmine.getEnv().addReporter(new CustomReporter(window.__karma__))
```

Thanks!
