### ISSUE TITLE
How to run integration-tests? 

### ISSUE THREAD

**Issue by srrvnn** [karma-runner/karma-jasmine#90]
Looking to contribute. How do I run integration tests after changes? 

    npm install
    ./integration-tests.sh. 

To get : 

    Firefox 38.0.0 (Mac OS X 10.10) ERROR
        You need to include some adapter that implements __karma__.start method!

**Comment by maksimr** [comment]
@srrvnn 

```sh
grunt build && ./integration-tests.sh
```

Thanks
