### ISSUE TITLE
Installing from repo with npm leaves adapater.js unavailable

### ISSUE THREAD

**Issue by sdcoca** [karma-runner/karma-jasmine#95]
Hi,

due to issue #85 I am needing to install directly from the repo and we need to automatize it.

I thought using command below should do the job but it leaves "lib/adapter.js" lacking and I cannot run grunt to build it since 'src' folder is not fetched by npm: 

sudo npm install git://github.com/karma-runner/karma-jasmine.git

Should lib/adapter.js go to the repo index as well?

Sergio.

**Comment by maksimr** [comment]
I don't think so. Because on every change you should manually rebuild sources

Feel free to reopen

Thank

**Comment by sdcoca** [comment]
No problem, with #85 fixed everything is nice now. Thanks!.
