### ISSUE TITLE
peerDependencies warning when installing via npm

### ISSUE THREAD

**Issue by alexgibson** [karma-runner/karma-jasmine#96]
npm install karma-jasmine --save-dev
    npm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no
    npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
    npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
    jasmine-core@2.3.4 node_modules/jasmine-core

**Comment by blackendstudios** [comment]
same to me

**Comment by nikshulipa** [comment]
+ 1 for this

**Comment by maksimr** [comment]
Thanks!
Which solution you propose?

**Comment by Dignifiedquire** [comment]
This warning is meant for people using `karma-jasmine` and not for the authors. When npm@3 will be released peerDependencies will work as they should have from the start, npm will warn you that they are missing but if you use `karma-jasmine` you will have to manually install/add `jasmine` to your project. So I'm not seeing an issue for use here.

**Comment by maksimr** [comment]
@Dignifiedquire Thanks! Sounds good :)
Then we can close the issue, right?

**Comment by alexgibson** [comment]
Thanks - I was initially confused by this, as my project does have `jasmine-core` in dev dependencies. Perhaps I installed them out of sequence. Either way, thanks for the clarification!

**Comment by shireefkhatab** [comment]
Thanks All
