### ISSUE TITLE
Version Release bump down to Release 0.1.6 from 0.3.6 causing npm install issues

### ISSUE THREAD

**Issue by provryan** [karma-runner/karma-jasmine#97]
I'm seeing npm install issues when running with 
```
"karma-jasmine": "latest",
``` 
in my packages.json file. I checked and it appears that if I target

```
"karma-jasmine": "~0.3.6",
```
npm installs correctly. Could this be an issue with a release made a4 hours ago to bump the version down to 0.1.6?

Thanks!

**Comment by Dignifiedquire** [comment]
Sorry about that, should be fixed now

```
❯ npm view karma-jasmine@latest version
0.3.6
```
